### PR TITLE
PT, update missing translations

### PR DESCRIPTION
**Pull request by itsphaze**

### CODE REVIEW

**Comment by austinhuang0131** [comment]
@SmokyBird

**Comment by SmokyBird** [comment]
@itsphaze I've noticed a couple things that could be discussed if you think it should be:

- Line 92: "Redirecting" means that it's occurring at the moment this message shows up. Maybe it could be translated to "Redireção"?
- Line 94: "Review" could be translated to "Resumo" or "Revista" (probably the first one, the second one could be mislead as a magazine)

**Comment by austinhuang0131** [comment]
wip due to unaddressed comments

**Comment by itsphaze** [comment]
I agree on the line 94. Although, "redireção" isn't an European Portuguese word and, for me, it looks more like an adjective other than a verb

**Pull request merged**
